"""add_address_number

Revision ID: 05f7d88ed758
Revises: 6425252b8110
Create Date: 2025-12-18 00:47:32.408298

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05f7d88ed758'
down_revision: Union[str, Sequence[str], None] = '6425252b8110'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('addresses', sa.Column('number', sa.String(), nullable=True))
    # op.drop_index('ix_addresses_id_key', table_name='addresses')
    # op.create_index(op.f('ix_addresses_street'), 'addresses', ['street'], unique=False)
    # op.drop_column('addresses', 'zip_code')
    # op.drop_column('addresses', 'state')
    # op.alter_column('bills', 'payment_type',
    #            existing_type=sa.INTEGER(),
    #            type_=sa.Enum('CASH', 'CARD', 'DEBIT', 'CREDIT', 'BANK_TRANSFER', name='paymenttype'),
    #            existing_nullable=True)
    # op.alter_column('bills', 'client_id',
    #            existing_type=sa.INTEGER(),
    #            nullable=True)
    # op.drop_constraint('bills_bill_number_key', 'bills', type_='unique')
    # op.drop_index('ix_bills_id_key', table_name='bills')
    # op.drop_index('ix_categories_id_key', table_name='categories')
    # op.create_index(op.f('ix_categories_name'), 'categories', ['name'], unique=True)
    # op.drop_constraint('clients_email_key', 'clients', type_='unique')
    # op.drop_index('ix_clients_id_key', table_name='clients')
    # op.create_index(op.f('ix_clients_lastname'), 'clients', ['lastname'], unique=False)
    # op.create_index(op.f('ix_clients_name'), 'clients', ['name'], unique=False)
    # op.drop_index('ix_order_details_id_key', table_name='order_details')
    # op.alter_column('orders', 'delivery_method',
    #            existing_type=sa.INTEGER(),
    #            type_=sa.Enum('DRIVE_THRU', 'ON_HAND', 'HOME_DELIVERY', name='deliverymethod'),
    #            existing_nullable=True)
    # op.alter_column('orders', 'status',
    #            existing_type=sa.INTEGER(),
    #            type_=sa.Enum('PENDING', 'IN_PROGRESS', 'DELIVERED', 'CANCELED', name='status'),
    #            existing_nullable=True)
    # op.drop_index('ix_orders_id_key', table_name='orders')
    # op.create_index(op.f('ix_orders_date'), 'orders', ['date'], unique=False)
    # op.create_index(op.f('ix_orders_delivery_method'), 'orders', ['delivery_method'], unique=False)
    # op.create_index(op.f('ix_orders_status'), 'orders', ['status'], unique=False)
    # op.alter_column('products', 'stock',
    #            existing_type=sa.INTEGER(),
    #            nullable=False)
    # op.drop_index('ix_products_id_key', table_name='products')
    # op.create_index(op.f('ix_products_name'), 'products', ['name'], unique=False)
    # op.create_index(op.f('ix_products_price'), 'products', ['price'], unique=False)
    # op.create_index(op.f('ix_products_stock'), 'products', ['stock'], unique=False)
    # op.drop_column('products', 'description')
    # op.drop_index('ix_reviews_id_key', table_name='reviews')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('addresses', 'number')
    # op.create_index('ix_reviews_id_key', 'reviews', ['id_key'], unique=False)
    # op.add_column('products', sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True))
    # op.drop_index(op.f('ix_products_stock'), table_name='products')
    # op.drop_index(op.f('ix_products_price'), table_name='products')
    # op.drop_index(op.f('ix_products_name'), table_name='products')
    # op.create_index('ix_products_id_key', 'products', ['id_key'], unique=False)
    # op.alter_column('products', 'stock',
    #            existing_type=sa.INTEGER(),
    #            nullable=True)
    # op.drop_index(op.f('ix_orders_status'), table_name='orders')
    # op.drop_index(op.f('ix_orders_delivery_method'), table_name='orders')
    # op.drop_index(op.f('ix_orders_date'), table_name='orders')
    # op.create_index('ix_orders_id_key', 'orders', ['id_key'], unique=False)
    # op.alter_column('orders', 'status',
    #            existing_type=sa.Enum('PENDING', 'IN_PROGRESS', 'DELIVERED', 'CANCELED', name='status'),
    #            type_=sa.INTEGER(),
    #            existing_nullable=True)
    # op.alter_column('orders', 'delivery_method',
    #            existing_type=sa.Enum('DRIVE_THRU', 'ON_HAND', 'HOME_DELIVERY', name='deliverymethod'),
    #            type_=sa.INTEGER(),
    #            existing_nullable=True)
    # op.create_index('ix_order_details_id_key', 'order_details', ['id_key'], unique=False)
    # op.drop_index(op.f('ix_clients_name'), table_name='clients')
    # op.drop_index(op.f('ix_clients_lastname'), table_name='clients')
    # op.create_index('ix_clients_id_key', 'clients', ['id_key'], unique=False)
    # op.create_unique_constraint('clients_email_key', 'clients', ['email'])
    # op.drop_index(op.f('ix_categories_name'), table_name='categories')
    # op.create_index('ix_categories_id_key', 'categories', ['id_key'], unique=False)
    # op.create_index('ix_bills_id_key', 'bills', ['id_key'], unique=False)
    # op.create_unique_constraint('bills_bill_number_key', 'bills', ['bill_number'])
    # op.alter_column('bills', 'client_id',
    #            existing_type=sa.INTEGER(),
    #            nullable=False)
    # op.alter_column('bills', 'payment_type',
    #            existing_type=sa.Enum('CASH', 'CARD', 'DEBIT', 'CREDIT', 'BANK_TRANSFER', name='paymenttype'),
    #            type_=sa.INTEGER(),
    #            existing_nullable=True)
    # op.add_column('addresses', sa.Column('state', sa.VARCHAR(), autoincrement=False, nullable=True))
    # op.add_column('addresses', sa.Column('zip_code', sa.VARCHAR(), autoincrement=False, nullable=True))
    # op.drop_index(op.f('ix_addresses_street'), table_name='addresses')
    # op.create_index('ix_addresses_id_key', 'addresses', ['id_key'], unique=False)
    # ### end Alembic commands ###
